services:
  nginx:
    image: nginx:latest
    container_name: roller_coaster_nginx
    ports:
      - "80:80"
    volumes:
      - ./project-root:/var/www/html:cached
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - roller-coaster-network

  php:
    build:
      context: ./.docker/php
    container_name: roller_coaster_php
    volumes:
      - ./project-root:/var/www/html:cached
    expose:
      - "9000"
    networks:
      - roller-coaster-network

  redis:
    image: redis:latest
    container_name: roller_coaster_redis
    command: redis-server --appendonly yes
    volumes:
      - .docker/redis/data:/data
    ports:
      - "6379:6379"
    networks:
      - roller-coaster-network

networks:
  roller-coaster-network:
    driver: bridge